name: delta-ci
on:
  workflow_call:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - '*.txt'
      - '.github/*'
      - 'docs/*'
      - 'fastlane/*'
  pull_request:
    types:
      - ready_for_review
      - review_requested
      - synchronize
    paths-ignore:
      - '*.md'
      - '*.txt'
      - '.github/*'
      - 'docs/*'
      - 'fastlane/*'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    name: Lint check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run lint check
        uses: ./.github/actions/run-lints
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          read-only-cache: github.event_name == 'pull_request'
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run unit tests
        uses: ./.github/actions/run-tests
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          read-only-cache: github.event_name == 'pull_request'
  dependency-graph-submission:
    name: Dependency graph submission
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Generate dependency graph
        uses: ./.github/actions/gradle-setup
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          gradle-action: dependency-submission
  upload-strings-to-crowdin:
    name: Upload string to crowdin
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Sync with crowdin
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          upload_translations: false
          download_translations: false
          create_pull_request: false
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PAT }}
