name: Release tasks
permissions:
  contents: read
  pull-requests: write
on:
  push:
    tags-ignore:
      - norel-*
  workflow_dispatch:
concurrency:
  group: release
  cancel-in-progress: true
jobs:
  # TODO: check if CI passed for tag
  build-apk:
    name: Build app
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build APK
        uses: ./.github/actions/build-apk
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          sign-release: true
          keystore-base64: ${{ secrets.KEYSTORE_BASE64 }}
          sign-base64: ${{ secrets.SIGN_BASE64 }}
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    needs: [build-apk]
    permissions:
      contents: write
      discussions: write
    steps:
      # TODO: use metadata from fastlane
      - name: Download APK
        uses: actions/download-artifact@v4
        with:
          name: app
      - name: Calculate checksum and generate release notes
        run: |
          cat << "EOF" >> release_notes.txt
          ### Message

          To be filled.

          ### Checksum

          ```sh
          $ sha256sum app-release.apk
          EOF

          sha256sum app-release.apk >> release_notes.txt

          cat << "EOF" >> release_notes.txt
          ```

          Check the checksum after downloading the APK using `sha256sum` to
          ensure integrity of the file.
          EOF
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          draft: true
          prerelease: false
          tag_name: ${{ needs.pre-release-job.outputs.version }}
          files: |
            app-release.apk
          discussion_category_name: Announcements
          body_path: release_notes.txt
